name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Publish & Deploy
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - name: Checkout Repo
        uses: actions/checkout@main
        with:
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v3.8.1
        with:
          node-version-file: '.nvmrc'

      - name: corepack
        run: corepack enable

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Create release PR or publish to npm
        uses: changesets/action@v1.4.5
        with:
          version: pnpm ci:version
          publish: pnpm ci:release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_RELEASE_TOKEN }}
