name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Publish & Deploy
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - name: Checkout Repo
        uses: actions/checkout@main

      - name: Setup Node.js 14.x
        uses: actions/setup-node@main
        with:
          node-version: 14.x

      - name: Install Dependencies
        run: pnpm install

      - name: Create release PR or publish to npm
        uses: changesets/action@master
        with:
          version: pnpm ci:version
          publish: pnpm ci:release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
